[package]
name = "artnet-udpled"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
artnet_protocol = { git = "https://github.com/sirrow/artnet_protocol.git", branch = "master"}
anyhow = "1.0"